# Generated by Django 6.0.5 on 2026-06-04 10:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalSessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('password_change', 'Alteração de Password')], db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_logs', to='portal.customeraccess')),
            ],
            options={
                'verbose_name': 'Registo de Sessão',
                'verbose_name_plural': 'Registos de Sessão',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['access', 'created_at'], name='portal_port_access__c2bc55_idx'), models.Index(fields=['access', 'action'], name='portal_port_access__db7438_idx')],
            },
        ),
    ]
