# Generated by Django 6.0.5 on 2026-06-04 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_add_portal_session_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatementShareToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=32, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_tokens', to='portal.customeraccess')),
            ],
            options={
                'verbose_name': 'Token de Partilha',
                'verbose_name_plural': 'Tokens de Partilha',
            },
        ),
    ]
