# Generated by Django 6.0.5 on 2026-05-22 17:06

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_deleted_at_payment_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(db_index=True, validators=[app.validators.validate_payment_date], verbose_name='Data'),
        ),
    ]
