# Generated by Django 6.0.5 on 2026-05-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_customer_email_alter_customer_nif_and_more'),
        ('payments', '0004_alter_payment_date'),
        ('suppliers', '0004_supplier_email_supplier_nif_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('type', 'RECEIPT'), ('customer__isnull', False), ('supplier__isnull', True)), models.Q(('type', 'PAYMENT'), ('supplier__isnull', False), ('customer__isnull', True)), _connector='OR'), name='payment_entity_required'),
        ),
    ]
