# Generated by Django 6.0.5 on 2026-05-26 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_add_check_constraints'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tenants.tenant'),
        ),
    ]
