# Generated by Django 6.0.5 on 2026-05-22 17:06

import app.validators
import django.core.validators
from django.db import migrations, models


def dedupe_supplier_nifs(apps, schema_editor):
    Supplier = apps.get_model('suppliers', 'Supplier')
    seen = set()
    for supplier in Supplier.objects.order_by('id'):
        nif = (getattr(supplier, 'nif', None) or '').strip()
        if not nif:
            if hasattr(supplier, 'nif'):
                supplier.nif = ''
                supplier.save(update_fields=['nif'])
            continue
        if nif in seen:
            supplier.nif = ''
            supplier.save(update_fields=['nif'])
        else:
            seen.add(nif)


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_supplier_deleted_at_supplier_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator(message='Introduza um endereço de email válido.')]),
        ),
        migrations.AddField(
            model_name='supplier',
            name='nif',
            field=models.CharField(blank=True, max_length=20, validators=[app.validators.validate_angolan_nif]),
        ),
        migrations.RunPython(dedupe_supplier_nifs, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(condition=models.Q(('nif__isnull', False), models.Q(('nif', ''), _negated=True)), fields=('nif',), name='supplier_nif_unique'),
        ),
    ]
