# Generated by Django 6.0.5 on 2026-05-26 09:56

import app.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_supplier_email_supplier_nif_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, validators=[django.core.validators.EmailValidator(message='Introduza um endereço de email válido.')]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='nif',
            field=models.CharField(blank=True, db_index=True, max_length=20, validators=[app.validators.validate_angolan_nif]),
        ),
    ]
