# Generated by Django 6.0.5 on 2026-05-26 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0005_add_indexes_and_constraints'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='supplier',
            name='supplier_nif_unique',
        ),
        migrations.AddField(
            model_name='supplier',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['tenant', 'name'], name='suppliers_s_tenant__566edc_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('nif__isnull', False), models.Q(('nif', ''), _negated=True)), fields=('tenant', 'nif'), name='supplier_tenant_nif_unique'),
        ),
    ]
