# Generated by Django 6.0.5 on 2026-05-29 13:56

import app.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0006_remove_supplier_supplier_nif_unique_supplier_tenant_and_more'),
        ('tenants', '0002_alter_tenant_options_alter_tenantsettings_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name'], 'verbose_name': 'Fornecedor', 'verbose_name_plural': 'Fornecedores'},
        ),
        migrations.AlterField(
            model_name='supplier',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, validators=[django.core.validators.EmailValidator(message='Introduza um endereço de email válido.')], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(db_index=True, max_length=500, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='nif',
            field=models.CharField(blank=True, db_index=True, max_length=20, validators=[app.validators.validate_angolan_nif], verbose_name='NIF'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['tenant', 'is_deleted'], name='suppliers_s_tenant__d43021_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['tenant', 'email'], name='suppliers_s_tenant__06d98a_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['tenant', 'nif'], name='suppliers_s_tenant__c457c1_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['tenant', 'created_at'], name='suppliers_s_tenant__366fce_idx'),
        ),
    ]
