# Generated by Django 6.0.5 on 2026-05-29 13:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['-created_at'], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='tenantsettings',
            options={'verbose_name': 'Configurações da Empresa', 'verbose_name_plural': 'Configurações da Empresa'},
        ),
        migrations.AlterModelOptions(
            name='tenantuser',
            options={'ordering': ['-joined_at'], 'verbose_name': 'Utilizador da Empresa', 'verbose_name_plural': 'Utilizadores da Empresa'},
        ),
        migrations.AlterField(
            model_name='tenant',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='api_key',
            field=models.CharField(blank=True, help_text='Guardado como hash — não recuperável.', max_length=255),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='tenantuser',
            index=models.Index(fields=['tenant', 'role'], name='tenants_ten_tenant__55a2cb_idx'),
        ),
    ]
