# Generated by Django 6.0.5 on 2026-05-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_driver_deleted_at_driver_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='cistern_plate',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Matrícula da Cisterna'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='truck_plate',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Matrícula do Caminhão'),
        ),
        migrations.AddConstraint(
            model_name='driver',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('truck_plate',), name='driver_truck_plate_unique'),
        ),
        migrations.AddConstraint(
            model_name='driver',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('cistern_plate',), name='driver_cistern_plate_unique'),
        ),
    ]
