# Generated by Django 6.0.5 on 2026-05-26 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_add_indexes_and_constraints'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='tenants.tenant'),
        ),
    ]
