# Generated by Django 6.0.5 on 2026-05-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_driver_tenant'),
        ('tenants', '0002_alter_tenant_options_alter_tenantsettings_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='driver',
            name='driver_truck_plate_unique',
        ),
        migrations.RemoveConstraint(
            model_name='driver',
            name='driver_cistern_plate_unique',
        ),
        migrations.AlterField(
            model_name='driver',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['tenant', 'is_deleted'], name='drivers_dri_tenant__c5f69e_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['tenant', 'name'], name='drivers_dri_tenant__cc404e_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['tenant', 'truck_plate'], name='drivers_dri_tenant__32dc6b_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['tenant', 'cistern_plate'], name='drivers_dri_tenant__e9d296_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['tenant', 'created_at'], name='drivers_dri_tenant__140d70_idx'),
        ),
        migrations.AddConstraint(
            model_name='driver',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('tenant', 'truck_plate'), name='driver_truck_plate_unique'),
        ),
        migrations.AddConstraint(
            model_name='driver',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('tenant', 'cistern_plate'), name='driver_cistern_plate_unique'),
        ),
    ]
