# Generated by Django 6.0.4 on 2026-05-08 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('inflows', '0001_initial'),
        ('outflows', '0003_alter_outflow_customer'),
        ('suppliers', '0002_alter_supplier_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAccountEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=500)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_entries', to='customers.customer')),
                ('outflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_entries', to='outflows.outflow')),
            ],
            options={
                'verbose_name': 'Customer Account Entry',
                'verbose_name_plural': 'Customer Account Entries',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SupplierAccountEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=500)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('inflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_entries', to='inflows.inflow')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_entries', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Supplier Account Entry',
                'verbose_name_plural': 'Supplier Account Entries',
                'ordering': ['-date'],
            },
        ),
    ]
