# Generated by Django 6.0.5 on 2026-05-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customeraccountentry_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccountentry',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='supplieraccountentry',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
