# Generated by Django 6.0.4 on 2026-05-18 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customeraccountentry_date_and_more'),
        ('inflows', '0004_alter_inflow_quantity'),
        ('outflows', '0007_delivery_actual_quantity_delivery_is_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccountentry',
            name='outflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_entries', to='outflows.outflow'),
        ),
        migrations.AlterField(
            model_name='supplieraccountentry',
            name='inflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_entries', to='inflows.inflow'),
        ),
    ]
