# Generated by Django 6.0.5 on 2026-05-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customeraccountentry_outflow_and_more'),
        ('customers', '0005_alter_customer_email_alter_customer_nif_and_more'),
        ('inflows', '0005_inflow_deleted_at_inflow_is_deleted'),
        ('outflows', '0008_outflow_deleted_at_outflow_is_deleted'),
        ('payments', '0004_alter_payment_date'),
        ('suppliers', '0004_supplier_email_supplier_nif_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customeraccountentry',
            index=models.Index(fields=['customer', 'date'], name='accounts_cu_custome_15c094_idx'),
        ),
        migrations.AddIndex(
            model_name='customeraccountentry',
            index=models.Index(fields=['customer', 'outflow'], name='accounts_cu_custome_d06129_idx'),
        ),
        migrations.AddIndex(
            model_name='supplieraccountentry',
            index=models.Index(fields=['supplier', 'date'], name='accounts_su_supplie_45037b_idx'),
        ),
        migrations.AddIndex(
            model_name='supplieraccountentry',
            index=models.Index(fields=['supplier', 'inflow'], name='accounts_su_supplie_98e88c_idx'),
        ),
    ]
