# Generated by Django 6.0.5 on 2026-05-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customeraccountentry_accounts_cu_custome_15c094_idx_and_more'),
        ('customers', '0005_alter_customer_email_alter_customer_nif_and_more'),
        ('inflows', '0006_alter_inflow_quantity_and_more'),
        ('outflows', '0010_add_delivery_indexes'),
        ('payments', '0004_alter_payment_date'),
        ('suppliers', '0004_supplier_email_supplier_nif_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customeraccountentry',
            constraint=models.CheckConstraint(condition=models.Q(('debit__gte', 0)), name='customer_entry_debit_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='customeraccountentry',
            constraint=models.CheckConstraint(condition=models.Q(('credit__gte', 0)), name='customer_entry_credit_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='customeraccountentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('debit__gt', 0), ('credit', 0)), models.Q(('credit__gt', 0), ('debit', 0)), _connector='OR'), name='customer_entry_debit_credit_exclusive'),
        ),
        migrations.AddConstraint(
            model_name='supplieraccountentry',
            constraint=models.CheckConstraint(condition=models.Q(('debit__gte', 0)), name='supplier_entry_debit_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='supplieraccountentry',
            constraint=models.CheckConstraint(condition=models.Q(('credit__gte', 0)), name='supplier_entry_credit_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='supplieraccountentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('debit__gt', 0), ('credit', 0)), models.Q(('credit__gt', 0), ('debit', 0)), _connector='OR'), name='supplier_entry_debit_credit_exclusive'),
        ),
    ]
