# Generated by Django 6.0.5 on 2026-05-26 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_check_constraints'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccountentry',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_account_entries', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='supplieraccountentry',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_account_entries', to='tenants.tenant'),
        ),
    ]
