# Generated by Django 6.0.5 on 2026-05-29 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customeraccountentry_tenant_and_more'),
        ('customers', '0008_alter_customer_options_alter_customer_address_and_more'),
        ('inflows', '0008_alter_inflow_options_alter_inflow_deleted_at_and_more'),
        ('outflows', '0013_alter_delivery_options_alter_outflow_options_and_more'),
        ('payments', '0007_alter_payment_amount_alter_payment_deleted_at_and_more'),
        ('suppliers', '0007_alter_supplier_options_alter_supplier_deleted_at_and_more'),
        ('tenants', '0002_alter_tenant_options_alter_tenantsettings_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeraccountentry',
            options={'ordering': ['-date'], 'verbose_name': 'Lançamento de Cliente', 'verbose_name_plural': 'Lançamentos de Clientes'},
        ),
        migrations.AlterModelOptions(
            name='supplieraccountentry',
            options={'ordering': ['-date'], 'verbose_name': 'Lançamento de Fornecedor', 'verbose_name_plural': 'Lançamentos de Fornecedores'},
        ),
        migrations.AlterField(
            model_name='customeraccountentry',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_entries', to='customers.customer', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='customeraccountentry',
            name='outflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_entries', to='outflows.outflow', verbose_name='Saída'),
        ),
        migrations.AlterField(
            model_name='customeraccountentry',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_account_entries', to='payments.payment', verbose_name='Pagamento'),
        ),
        migrations.AlterField(
            model_name='supplieraccountentry',
            name='inflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_entries', to='inflows.inflow', verbose_name='Entrada'),
        ),
        migrations.AlterField(
            model_name='supplieraccountentry',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_account_entries', to='payments.payment', verbose_name='Pagamento'),
        ),
        migrations.AlterField(
            model_name='supplieraccountentry',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_entries', to='suppliers.supplier', verbose_name='Fornecedor'),
        ),
        migrations.AddIndex(
            model_name='customeraccountentry',
            index=models.Index(fields=['tenant', 'customer'], name='accounts_cu_tenant__321ae2_idx'),
        ),
        migrations.AddIndex(
            model_name='customeraccountentry',
            index=models.Index(fields=['tenant', 'date'], name='accounts_cu_tenant__bcd3da_idx'),
        ),
        migrations.AddIndex(
            model_name='supplieraccountentry',
            index=models.Index(fields=['tenant', 'supplier'], name='accounts_su_tenant__1b0a02_idx'),
        ),
        migrations.AddIndex(
            model_name='supplieraccountentry',
            index=models.Index(fields=['tenant', 'date'], name='accounts_su_tenant__8087ab_idx'),
        ),
    ]
