# Generated by Django 6.0.5 on 2026-06-10 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0003_tenant_address_tenant_email_tenant_nif_tenant_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='ID da Task')),
                ('report_type', models.CharField(choices=[('outflows_by_customer', 'Saídas por Cliente'), ('deliveries', 'Entregas'), ('customer_account', 'Extrato de Clientes'), ('supplier_account', 'Extrato de Fornecedores'), ('balances', 'Saldos')], max_length=100, verbose_name='Tipo de Relatório')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Concluído'), ('failed', 'Falhou')], default='pending', max_length=20, verbose_name='Estado')),
                ('filters', models.JSONField(default=dict, verbose_name='Filtros')),
                ('export_format', models.CharField(default='excel', max_length=10, verbose_name='Formato')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='Caminho do Ficheiro')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='Empresa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
            ],
            options={
                'verbose_name': 'Job de Exportação',
                'verbose_name_plural': 'Jobs de Exportação',
                'ordering': ['-created_at'],
            },
        ),
    ]
