# Generated by Django 6.0.5 on 2026-05-26 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_add_indexes_and_constraints'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='category_name_unique',
        ),
        migrations.AddField(
            model_name='category',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['tenant', 'name'], name='categories__tenant__d0de14_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('tenant', 'name'), name='category_name_unique_per_tenant'),
        ),
    ]
