# Generated by Django 6.0.4 on 2026-05-09 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
        ('outflows', '0003_alter_outflow_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Entrega'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='destination',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Local da Entrega'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='drivers.driver', verbose_name='Motorista'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nº da Factura Associada'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='origin',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Origem do Produto'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Receptor'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='shipping_guide_file',
            field=models.FileField(blank=True, null=True, upload_to='shipping_guides/', verbose_name='Anexo da Guia'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='shipping_guide_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nº Guia de Remessa'),
        ),
        migrations.AddField(
            model_name='outflow',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Preço de Saída'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='quantity',
            field=models.IntegerField(verbose_name='Quantidade Entregue'),
        ),
    ]
