# Generated by Django 6.0.5 on 2026-05-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0004_delivery_delivery_date_delivery_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivered_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='outflow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='outflow',
            name='quantity_delivered',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
