# Generated by Django 6.0.5 on 2026-05-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0005_alter_delivery_delivered_at_alter_outflow_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=20, verbose_name='Quantidade Entregue'),
        ),
        migrations.AlterField(
            model_name='outflow',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='outflow',
            name='quantity_delivered',
            field=models.DecimalField(db_index=True, decimal_places=4, default=0, max_digits=20),
        ),
    ]
