# Generated by Django 6.0.5 on 2026-05-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0006_alter_delivery_quantity_alter_outflow_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='actual_quantity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Quantidade Real (Balança)'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Confirmado na Balança'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=20, verbose_name='Quantidade Estimada'),
        ),
    ]
