# Generated by Django 6.0.5 on 2026-05-22 17:06

import app.validators
import django.core.validators
import outflows.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_customer_email_alter_customer_nif_and_more'),
        ('drivers', '0002_driver_deleted_at_driver_is_deleted'),
        ('outflows', '0008_outflow_deleted_at_outflow_is_deleted'),
        ('products', '0006_product_deleted_at_product_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Quantidade Estimada'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='shipping_guide_file',
            field=models.FileField(blank=True, null=True, upload_to='shipping_guides/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), outflows.models.validate_file_size, app.validators.validate_file_content], verbose_name='Anexo da Guia'),
        ),
        migrations.AlterField(
            model_name='outflow',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0001)]),
        ),
        migrations.AddIndex(
            model_name='outflow',
            index=models.Index(fields=['customer', 'created_at'], name='outflows_ou_custome_0dd3ee_idx'),
        ),
        migrations.AddIndex(
            model_name='outflow',
            index=models.Index(fields=['product', 'created_at'], name='outflows_ou_product_b96e71_idx'),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='delivery_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='outflow',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='outflow_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='outflow',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_delivered__gte', 0)), name='outflow_quantity_delivered_non_negative'),
        ),
    ]
