# Generated by Django 6.0.5 on 2026-05-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_driver_deleted_at_driver_is_deleted'),
        ('outflows', '0009_delivery_deleted_at_delivery_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['outflow', 'delivered_at'], name='outflows_de_outflow_602667_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['driver', 'delivered_at'], name='outflows_de_driver__f831e2_idx'),
        ),
    ]
