# Generated by Django 6.0.5 on 2026-05-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0010_add_delivery_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='outflow',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('partial', 'Parcial'), ('delivered', 'Entregue')], db_index=True, default='pending', max_length=20, verbose_name='Estado'),
        ),
    ]
