# Generated by Django 6.0.5 on 2026-05-26 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0011_add_status_field'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='outflow',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outflows', to='tenants.tenant'),
        ),
    ]
