# Generated by Django 6.0.5 on 2026-05-29 13:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_alter_customer_options_alter_customer_address_and_more'),
        ('drivers', '0005_remove_driver_driver_truck_plate_unique_and_more'),
        ('outflows', '0012_delivery_tenant_outflow_tenant'),
        ('products', '0009_alter_product_options_and_more'),
        ('tenants', '0002_alter_tenant_options_alter_tenantsettings_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['-delivered_at'], 'verbose_name': 'Entrega', 'verbose_name_plural': 'Entregas'},
        ),
        migrations.AlterModelOptions(
            name='outflow',
            options={'ordering': ['-created_at'], 'verbose_name': 'Saída', 'verbose_name_plural': 'Saídas'},
        ),
        migrations.AddField(
            model_name='delivery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='actual_quantity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade Real (Balança)'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivered_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='outflow',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outflows', to='customers.customer', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='outflow',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='outflow',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='outflow',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço de Saída'),
        ),
        migrations.AlterField(
            model_name='outflow',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outflows', to='products.product', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='outflow',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='outflow',
            name='quantity_delivered',
            field=models.DecimalField(db_index=True, decimal_places=4, default=0, max_digits=20, verbose_name='Quantidade Entregue'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['tenant', 'is_deleted'], name='outflows_de_tenant__73e33e_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['tenant', 'delivered_at'], name='outflows_de_tenant__a4a7e1_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['tenant', 'driver'], name='outflows_de_tenant__0b3b47_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['tenant', 'outflow'], name='outflows_de_tenant__2fd810_idx'),
        ),
        migrations.AddIndex(
            model_name='outflow',
            index=models.Index(fields=['tenant', 'is_deleted'], name='outflows_ou_tenant__0c1b76_idx'),
        ),
        migrations.AddIndex(
            model_name='outflow',
            index=models.Index(fields=['tenant', 'created_at'], name='outflows_ou_tenant__ddfcb9_idx'),
        ),
        migrations.AddIndex(
            model_name='outflow',
            index=models.Index(fields=['tenant', 'customer'], name='outflows_ou_tenant__646d70_idx'),
        ),
        migrations.AddIndex(
            model_name='outflow',
            index=models.Index(fields=['tenant', 'product'], name='outflows_ou_tenant__72e906_idx'),
        ),
        migrations.AddIndex(
            model_name='outflow',
            index=models.Index(fields=['tenant', 'status'], name='outflows_ou_tenant__780130_idx'),
        ),
    ]
