# Generated by Django 6.0.5 on 2026-05-22 17:06

import app.validators
import django.core.validators
from django.db import migrations, models


def dedupe_customer_nifs(apps, schema_editor):
    Customer = apps.get_model('customers', 'Customer')
    seen = set()
    for customer in Customer.objects.order_by('id'):
        nif = (customer.nif or '').strip()
        if not nif:
            customer.nif = ''
            customer.save(update_fields=['nif'])
            continue
        if nif in seen:
            customer.nif = ''
            customer.save(update_fields=['nif'])
        else:
            seen.add(nif)


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_deleted_at_customer_is_deleted'),
    ]

    operations = [
        migrations.RunPython(dedupe_customer_nifs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator(message='Introduza um endereço de email válido.')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nif',
            field=models.CharField(blank=True, max_length=20, validators=[app.validators.validate_angolan_nif]),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('nif__isnull', False), models.Q(('nif', ''), _negated=True)), fields=('nif',), name='customer_nif_unique'),
        ),
    ]
