# Generated by Django 6.0.5 on 2026-05-29 13:56

import app.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_remove_customer_customer_nif_unique_customer_tenant_and_more'),
        ('tenants', '0002_alter_tenant_options_alter_tenantsettings_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, validators=[django.core.validators.EmailValidator(message='Introduza um endereço de email válido.')], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(db_index=True, max_length=500, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nif',
            field=models.CharField(blank=True, db_index=True, max_length=20, validators=[app.validators.validate_angolan_nif], verbose_name='NIF'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Telefone'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['tenant', 'is_deleted'], name='customers_c_tenant__a2c953_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['tenant', 'created_at'], name='customers_c_tenant__7bbedf_idx'),
        ),
    ]
