# Generated by Django 6.0.5 on 2026-06-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_alter_customer_options_alter_customer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='customers/photos/', verbose_name='Foto/Logótipo'),
        ),
    ]
