# Generated by Django 6.0.5 on 2026-05-29 13:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_auditlog_tenant'),
        ('tenants', '0002_alter_tenant_options_alter_tenantsettings_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['tenant', 'timestamp'], name='audit_audit_tenant__7e6e1d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['tenant', 'action'], name='audit_audit_tenant__b14d1a_idx'),
        ),
    ]
