# Generated by Django 6.0.5 on 2026-05-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflows', '0002_alter_inflow_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='inflow',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Preço de Custo'),
        ),
    ]
