# Generated by Django 6.0.5 on 2026-05-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflows', '0003_inflow_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inflow',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
    ]
