# Generated by Django 6.0.5 on 2026-05-22 17:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflows', '0005_inflow_deleted_at_inflow_is_deleted'),
        ('products', '0006_product_deleted_at_product_is_deleted'),
        ('suppliers', '0004_supplier_email_supplier_nif_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inflow',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0001)]),
        ),
        migrations.AddIndex(
            model_name='inflow',
            index=models.Index(fields=['supplier', 'created_at'], name='inflows_inf_supplie_8efbf4_idx'),
        ),
        migrations.AddIndex(
            model_name='inflow',
            index=models.Index(fields=['product', 'created_at'], name='inflows_inf_product_697a77_idx'),
        ),
        migrations.AddConstraint(
            model_name='inflow',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='inflow_quantity_positive'),
        ),
    ]
