# Generated by Django 6.0.5 on 2026-05-29 13:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflows', '0007_inflow_tenant'),
        ('products', '0009_alter_product_options_and_more'),
        ('suppliers', '0007_alter_supplier_options_alter_supplier_deleted_at_and_more'),
        ('tenants', '0002_alter_tenant_options_alter_tenantsettings_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inflow',
            options={'ordering': ['-created_at'], 'verbose_name': 'Entrada', 'verbose_name_plural': 'Entradas'},
        ),
        migrations.AlterField(
            model_name='inflow',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='inflow',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='inflow',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço de Custo'),
        ),
        migrations.AlterField(
            model_name='inflow',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inflows', to='products.product', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='inflow',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='inflow',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inflows', to='suppliers.supplier', verbose_name='Fornecedor'),
        ),
        migrations.AddIndex(
            model_name='inflow',
            index=models.Index(fields=['tenant', 'is_deleted'], name='inflows_inf_tenant__333d8c_idx'),
        ),
        migrations.AddIndex(
            model_name='inflow',
            index=models.Index(fields=['tenant', 'created_at'], name='inflows_inf_tenant__e9e867_idx'),
        ),
        migrations.AddIndex(
            model_name='inflow',
            index=models.Index(fields=['tenant', 'supplier'], name='inflows_inf_tenant__be86bd_idx'),
        ),
        migrations.AddIndex(
            model_name='inflow',
            index=models.Index(fields=['tenant', 'product'], name='inflows_inf_tenant__0c2ab2_idx'),
        ),
    ]
