# Generated by Django 6.0.5 on 2026-05-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
    ]
