# Generated by Django 6.0.4 on 2026-05-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('categories', '0001_initial'),
        ('products', '0004_alter_product_quantity'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='product_quantity_non_negative'),
        ),
    ]
