# Generated by Django 6.0.5 on 2026-05-22 17:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_brand_deleted_at_brand_is_deleted'),
        ('categories', '0003_category_deleted_at_category_is_deleted'),
        ('products', '0006_product_deleted_at_product_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('serial_number__isnull', False), models.Q(('serial_number', ''), _negated=True)), fields=('serial_number',), name='product_serial_number_unique'),
        ),
    ]
